# This workflow is to automate Checkmarx SCA scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_SCA_USERNAME
#   - CHECKMARX_SCA_PASSWORD
#
# The following variables must be inserted below:
#   - <ProjectName>
#   - <SCATenant>
#   - <GitHubRepoUrl>
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: Checkmarx SCA Scan
on:
  push:
    branches:
      - main    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9 # GitHub Action version
      with:
        project: ${{secrets.SCA_PROJECTNAME}}  # <-- Insert Checkmarx CxSCA Project Name
        sca_api_url: https://api-sca.checkmarx.net
        sca_app_url: https://sca.checkmarx.net
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: ${{secrets.SCA_TENANT}}  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{secrets.SCA_USERNAME}} # To be stored in GitHub Secrets.
        sca_password: ${{secrets.SCA_PASSWORD}} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sca
        bug_tracker: Sarif
        params: --github --enable-zip-scan=true --include-sources=true  --cx-project="KB_JVL_CxFlow_GHA_SCAResolver" --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.main }} --repo-url=${{github.repository.url}} --cx-flow.filterSeverity --cx-flow.filterCategory 
